"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/lib/context/auth-context";
import { collection, query, where, getDocs } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { HackerText } from "@/components/ui/hacker-text";
import { Button } from "@/components/ui/button";
import { Background } from "@/components/ui/background";
import { MagneticWrapper } from "@/components/ui/magnetic-wrapper";
import { Copy, Users, Zap, TrendingUp, Share2, Network, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { useSfx } from "@/hooks/use-sfx";

export default function ReferralPage() {
  const { userData } = useAuth();
  const { play } = useSfx();
  const [recruitCount, setRecruitCount] = useState(0);
  const [velocityCommission, setVelocityCommission] = useState(0);
  const [loading, setLoading] = useState(true);

  // FETCH RECRUITS
  useEffect(() => {
    const fetchRecruits = async () => {
      // Wait for auth to be ready
      if (!userData) {
         // Only stop loading if we are sure there is no user (e.g. auth failed), 
         // but usually useAuth handles the redirect.
         return; 
      }
      
      try {
        // Query users where 'invitedBy' == my uid
        // NOTE: Requires a Firestore Index on 'invitedBy'. 
        // If console shows an error link, click it to create the index.
        const q = query(collection(db, "users"), where("invitedBy", "==", userData.uid));
        const snap = await getDocs(q);
        
        setRecruitCount(snap.size);
        
        // Mock calculation: 150 Velocity per recruit
        setVelocityCommission(snap.size * 150); 
      } catch (e) {
        console.error("Failed to load recruits", e);
        toast.error("DATA_SYNC_FAILED");
      } finally {
        setLoading(false);
      }
    };

    fetchRecruits();
  }, [userData]);

  const copyCode = () => {
    if (!userData) return;
    play("click");
    
    // Fallback for SSR/Localhost logic
    const origin = typeof window !== 'undefined' ? window.location.origin : 'https://bubblepops.com';
    const code = `${origin}/auth/signup?ref=${userData.uid}`;
    
    navigator.clipboard.writeText(code);
    toast.success("UPLINK COPIED TO CLIPBOARD");
  };

  // SKELETON LOADER
  if (!userData || loading) {
    return (
      <div className="min-h-screen bg-black flex flex-col items-center justify-center space-y-4">
         <Loader2 className="w-10 h-10 text-purple-500 animate-spin" />
         <p className="text-xs font-mono text-purple-500/50 animate-pulse">CALCULATING NETWORK GRAPH...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#050505] p-6 pb-24 relative overflow-x-hidden font-sans text-white">
      
      <div className="fixed inset-0 z-0">
        <Background />
      </div>

      <div className="relative z-10 max-w-3xl mx-auto space-y-12 pt-8">
        
        {/* HEADER */}
        <div className="text-center space-y-4">
          <div className="relative w-20 h-20 mx-auto bg-purple-900/20 rounded-full flex items-center justify-center border border-purple-500/50 shadow-[0_0_30px_rgba(168,85,247,0.3)]">
            <Network className="w-10 h-10 text-purple-500" />
            <div className="absolute inset-0 rounded-full border border-purple-500/20 animate-[spin_10s_linear_infinite]" />
          </div>
          
          <div>
            <h1 className="text-4xl font-black font-orbitron text-white tracking-wide">
              <HackerText text="THE HIERARCHY" />
            </h1>
            <p className="text-gray-400 text-sm max-w-md mx-auto mt-2 leading-relaxed font-mono">
              Build your downline. Earn <span className="text-cyan-400 font-bold">10% of the Velocity</span> generated by every operative you recruit.
            </p>
          </div>
        </div>

        {/* STATS GRID */}
        <div className="grid grid-cols-2 gap-4 md:gap-6">
          <div className="bg-[#0A0A0A]/80 backdrop-blur-md border border-white/10 p-6 md:p-8 rounded-2xl text-center group hover:border-purple-500/50 transition-all">
              <p className="text-xs text-gray-500 uppercase tracking-[0.2em] mb-2 font-mono flex items-center justify-center gap-2">
                 <Users className="w-3 h-3" /> RECRUITS
              </p>
              <p className="text-4xl md:text-5xl font-black text-white font-orbitron group-hover:scale-110 transition-transform">
                {recruitCount}
              </p>
          </div>
          <div className="bg-[#0A0A0A]/80 backdrop-blur-md border border-white/10 p-6 md:p-8 rounded-2xl text-center group hover:border-cyan-500/50 transition-all">
              <p className="text-xs text-gray-500 uppercase tracking-[0.2em] mb-2 font-mono flex items-center justify-center gap-2">
                 <Zap className="w-3 h-3 text-cyan-500" /> PASSIVE VELOCITY
              </p>
              <div className="flex items-center justify-center gap-1 text-cyan-400 group-hover:scale-110 transition-transform">
                <p className="text-4xl md:text-5xl font-black font-orbitron">
                    +{velocityCommission}
                </p>
              </div>
          </div>
        </div>

        {/* INVITE LINK CARD */}
        <div className="bg-gradient-to-r from-purple-900/20 to-black border border-purple-500/30 p-8 rounded-2xl relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-1 h-full bg-purple-500 shadow-[0_0_15px_#a855f7]" />
          
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-6 gap-4">
             <div>
                <h3 className="text-xl font-bold text-white mb-1 flex items-center gap-2 font-orbitron tracking-wide">
                    <TrendingUp className="w-5 h-5 text-purple-400" /> YOUR RECRUITMENT LINK
                </h3>
                <p className="text-xs text-purple-200/60 font-mono">Share this uplink to bind new operatives to your node.</p>
             </div>
             <div className="bg-purple-500/10 border border-purple-500/20 px-3 py-1 rounded text-[10px] text-purple-400 font-bold uppercase tracking-widest animate-pulse">
                Commission Active
             </div>
          </div>
          
          <div className="flex gap-3">
            <div className="flex-1 bg-black/60 border border-purple-500/20 rounded-lg p-4 font-mono text-sm text-gray-300 truncate select-all hover:bg-black/80 transition-colors">
              {`${typeof window !== 'undefined' ? window.location.origin : 'https://bubblepops.com'}/auth/signup?ref=${userData.uid}`}
            </div>
            <MagneticWrapper>
                <Button 
                    onClick={copyCode} 
                    onMouseEnter={() => play("hover")}
                    className="bg-purple-600 hover:bg-purple-500 text-white font-bold h-full px-6 shadow-[0_0_20px_rgba(147,51,234,0.3)] transition-all hover:scale-105"
                >
                    <Copy className="w-5 h-5" />
                </Button>
            </MagneticWrapper>
          </div>
          
          <div className="mt-4 flex items-center gap-4 text-[10px] text-gray-500 font-mono border-t border-purple-500/10 pt-4">
             <span className="flex items-center gap-1">
                <Share2 className="w-3 h-3" /> Auto-Sync: Daily 00:00 UTC
             </span>
             <span className="w-1 h-1 rounded-full bg-gray-700" />
             <span>Tier 1 Commission: 10%</span>
          </div>
        </div>

      </div>
    </div>
  );
}